OZ-Coding-School/oz_01_main-004-FE

- frontend/app/page.tsx
> [develop]브랜치 실험

- front/package.json
- front/yarn.lock
ck에디터 오류로 인해 빌드가 안되서ckeditor  삭제
> [featrue/initial-setting] ckeditor 삭제

- netlify.toml
> [feature/initial-setting] netlify.toml 추가

- netlify.toml
> [feature/initail-setting]netlify.tomi 수정

- front/package.json
- front/yarn.lock
> [feature/initail-setting] yarn netlify 플러그인 설치

- netlify.toml
> [feature/initial-setting]netlify.tomi 삭제

- front/package.json
> [feature/initial-setting] netlify 재설치 및 toml파일 추가

- netlify.toml
> [feature/initial-setting]toml파일 재추가

- front/app/chat/page.tsx
- front/app/layout.tsx
- front/vercel.json
> [feature/initial-settin]vercel.json추가

- front/app/chat/page.tsx
- front/app/layout.tsx
- front/vercel.json
- netlify.toml
> [Develop] 배포를 위해 vercel.json 추가

- front/shared/components/nav/loginBtn/loginBtn.tsx
- front/shared/components/nav/nav.tsx
> [feature/login] 로그인 버튼 오류 수정

- front/package.json
- front/shared/components/nav/loginBtn/loginbutton.tsx
- front/shared/components/nav/nav.tsx
- front/yarn.lock
> [feature/login]react quil 추가

- .gitignore
- front/.env
- front/shared/api/axios.ts
> [feature/login] git-ignore 이슈

- front/shared/components/public/Button/Button.module.css
- front/shared/components/public/Button/Button.tsx
- front/shared/components/public/Input/Input.module.css
- front/shared/components/public/Input/Input.tsx
> [feature/public-component]button, input 공용컴포넌트 추가

- package.json
- src/components/Button/Button.tsx
- src/components/Input/Input.tsx
- src/pages/sign_up/index.module.css
- src/pages/sign_up/index.tsx
- yarn.lock
> [feature/signup] Feat: signup page 구현

- src/App.css
- src/App.tsx
- src/components/nav/nav.module.css
- src/pages/chat/chat.tsx
- src/pages/chat/index.module.css
- src/pages/chat/index.tsx
- src/pages/login/index.module.css
- src/pages/login/index.tsx
- src/pages/login/kakao/kakao.tsx
> [feature/searchbar] chatting room

- src/components/nav/nav.module.css
- src/pages/login/index.tsx
- src/pages/mypage /index.module.css
- src/pages/mypage /index.tsx
- src/pages/mypage /myprofile/my_profile.tsx
- src/pages/mypage /myprofile/myprofile.module.css
- src/pages/mypage /myprofile/myprofile.tsx
- src/pages/sign_up/index.module.css
- src/pages/sign_up/index.tsx
로그인 비밀번호 눈 보이기, 마이페이지 왼쪽바 수정및 색추가
> [feature/myinfo]Style: login password 눈 및 mypage 왼쪽바추가

- netlify.toml
- src/pages/chat/create_chat/create_chat.tsx
- src/pages/mypage /myprofile/myprofile.tsx
- src/pages/sign_up/index.tsx
> [feature/sokect]Chore: 빌드 환경 구성

- src/pages/login/index.tsx
- src/pages/login/kakao/kakao.tsx
- src/pages/login/set_auth_to_local/set_auth_to_local.tsx
카카오톡 로그인 시 로컬호스트로 가는 문제로 인한 코드수정
> [feature/sokect]Fix: 배포시 카카오톡 로그인 오류

- src/pages/login/index.tsx
- src/pages/login/kakao/kakao.tsx
from을 ssession에 저장 , 로그인 성공 시 이동시키고 session 삭제
> [feature/sokect]Fix: 카카오로그인 시  이전 페이지 이동 문제

- src/pages/login/index.tsx
- src/pages/login/kakao/kakao.tsx
- src/pages/login/set_auth_to_local/set_auth_to_local.tsx
any Type 이었던 setUserInfo를 보다 정확히 Type명시
> [feature/chat-func]Refactor: setUserInfo Type 지정

- package.json
- src/App.tsx
- src/components/nav/nav.tsx
- src/pages/chat/create_chat/create_chat.tsx
- src/pages/community/index.module.css
- src/pages/community/index.tsx
- src/pages/login/kakao/kakao.tsx
- yarn.lock
communityPage에 useParams 추가, 카카오 로그인 시 페이지 이동실패하는 버그 수정, 미비된 setUserInfo 타입 명시 ,
react-quill image-actions , formats 설치 , zustand 설치
> [feature/chat-func]Feat: communityPage에 useParams 기능 추가,카카오로그인 페이지이동 버그 해결

- src/pages/chat/create_chat/create_chat.tsx
빌드가 실패하여 안쓰는 코드제거 및 yarn build 재실행
> [feature/chat-func]Fix: 빌드실패로 인한 yarn build 재실행

- src/components/nav/nav.tsx
nav바에서 검색하면 , 커뮤니티 최신글로 가도록 함수 작성 및 적용
> [feature/chat-func]Feat: Nav바에 search 기능구현

- src/components/category/dropdow.tsx
- src/components/category/dropdown.module.css
- src/components/category/foodingredient.ts
- src/components/category/foodtype.ts
- src/components/selectbox/selectbox.tsx
- src/components/tagbutton/tagbutton.tsx
- src/pages/community/community.module.css
- src/pages/community/index.tsx
- src/pages/mypage /index.module.css
tagbutton, select, dropdown 컴포넌트 추가 및 커뮤니티 페이지 수
정
> [feature/category]Style: tagbutton, select, dropdown 컴포넌트 추가

- src/pages/chat/index.tsx
- src/pages/detail_post/index.module.css
- src/pages/detail_post/index.tsx
- src/pages/login/index.tsx
> [feature/nav-func]Style: detailPost Page 스타일링

- src/pages/mypage /index.tsx
- src/pages/mypage /myprofile/myprofile.tsx
> [feature/writePost]Fix: 배포시 버그 수정 완료

- src/pages/detail_post/index.module.css
- src/pages/detail_post/index.tsx
> [feature/nav-func]Style: 게시글 상세페이지 스타일 적용

- src/App.tsx
- src/components/category/dropdown.tsx
- src/components/nav/loginmypage/nevmypage.module.css
- src/components/nav/loginmypage/nevmypage.tsx
- src/components/nav/nav.module.css
- src/components/nav/nav.tsx
- src/pages/community/fooddata.ts
- src/pages/community/index.module.css
- src/pages/community/index.tsx
> [feature/category]Style: nav바 스타일 변경, 카테고리 api 연동

- setupProxy.js
- src/pages/write_post/index.tsx
> [feature/write-fn]Fix: proxy 설정

- package.json
- src/components/nav/nav.tsx
- src/pages/detail_post/actionnav.module.css
- src/pages/detail_post/actionnav.tsx
- src/pages/detail_post/index.tsx
- src/pages/write_post/index.tsx
- yarn.lock
블로그형식의 내용과 사진 가져오기 완성, 상세 게시글쪽 드롭다운 시도
해볼것: 정렬은 안나타나서 시도 해봐야함
> [feature/write-fn]Refactor: detailPost 내용 가져오기

- src/components/mealgrid/mealgrid.tsx
- src/components/mealgrid/type.ts
- src/pages/community/postlist/repostlist.tsx
- src/pages/main/index.tsx
- src/pages/mypage /likelist/likelist.tsx
- src/pages/mypage /mypost/mypost.module.css
- src/pages/mypage /mypost/mypost.tsx
mealgrid컴포넌트 재사용성을 위해 수정, mainpage 및 다른 페이지들도 그에 맞춰 수정 및 api 연결 완료
> [feature/mypost]Feat: mealgrid컴포넌트 수정, mainpage, likelist, mypost api 수정 및 연결

- package.json
- src/App.tsx
- src/api/axios.ts
- src/pages/chat/create_chat/create_chat.tsx
- src/pages/loading/loading.tsx
- store/loading_store.ts
- yarn.lock
zustand를 이용해 전역값으로 axios 요청에 대한 로딩페이지 구현 ,
API 콜할 떄 Headers 입력을 하지 않기 위해 instance에 axios Headers 설정
> [Feature/chatting]Feat: 로딩페이지 , axios Headers 설정

- src/pages/main/index.tsx
- src/pages/mypage /likelist/likelist.tsx
- src/pages/mypage /mypost/mypost.tsx
기존 mealgrid컴포넌트로 사용한 페이지에서 postcard컴포넌트로 대체 완료
> [feature/mypost]Fix: accesstoken 오류와 postcard컴포넌트로 대체 완료

- src/api/axios.ts
- src/pages/chat/create_chatroom/create_chatroom.tsx
- src/pages/chat/get_messages_of_chatroom/get_messages_of_chatroom.tsx
- src/pages/chat/get_my_chat_list/get_chat_list.tsx
- src/pages/chat/index.module.css
- src/pages/chat/index.tsx
- src/pages/chat/post_chat/post_chat.tsx
- src/pages/main/index.tsx
- src/type/chat.ts
채팅데이터 받아오기,컴포넌트 나누기 , chat 페이지네이션 , 디자인 작업
> [Feature/chatting] 채팅데이터 받아오기,컴포넌트 나누기 , chat 페이지네이션 , 디자인 작업

- src/pages/detail_post/comments/comments.tsx
- src/type/comments.ts
채팅 등록,수정 시에  refetch 안하도록 기능구현
> [feature/chatting]Feat: 채팅 기능구현

- src/components/postcard/postcard.module.css
- src/pages/community/postlist/recipelist.type.ts
- src/pages/main/index.tsx
- src/pages/mypage /mypost/mypost.tsx
mypost 내에서 여러글 작성되었을 때 삭제/버튼 확인되지 않았던 오류 수정
> [feature/mypost] Fix:메인페이지 style 컴포넌트 콘솔 오류 수정, mypost 삭제/수정 버튼 수정

- src/pages/sign_up/index.tsx
회원가입 이메일 중복확인 코드 추가
해야할것: 중복확인시 버튼 disabled 추가
> [feature/actionNav]Feat: signup email 중복확인 추가

- src/pages/detail_post/index.module.css
- src/pages/detail_post/index.tsx
- src/pages/detail_post/modify/modifypost.tsx
- src/pages/sign_up/index.tsx
이메일 중복확인시 중복일시 에러메세지, 중복아닐시 중복확인 버튼 disabled
> [feature/actionNav]Refactor: 이메일 중복확인 코드 리팩토링

- src/api/axios.ts
- src/components/nav/nav.tsx
- src/pages/detail_post/index.tsx
내 게시글에만 수정, 삭제  보이게 기능개선, 400에러 alert창 주석처리
> [feature/category]Feat: 내 게시글에만 수정, 삭제  보이게 기능개선, 400에러 alert창 주석처리

- src/components/category/dropdown.tsx
- src/components/tagbutton/tagbutton.tsx
- src/pages/community/querystring/querystringdropdown.tsx
- src/pages/community/querystring/querytagbutton.tsx
- src/pages/detail_post/actionnav.tsx
- src/pages/detail_post/index.tsx
- src/pages/detail_post/modify/modifypost.tsx
- src/pages/mypage /mypost/mypost.tsx
- src/pages/sign_up/index.tsx
- src/pages/write_post/index.tsx
수정페이지 종류,재료,태그 불러오기로 인해 dropdown, tagbutton, querystringdropdown 코드 수정, actionNav 수정, 삭제버튼 수정, 수정페이지에서 이미 있는 이미지 url 가져오고 삭제 및 추가 url 넘겨주기
> [feature/actionNav]Refactor: modify page dropDown, tag 불러오기, querystringdropdown 수정, actionNav 버튼수정

- src/pages/community/querystring/querystringdropdown.tsx
- src/pages/detail_post/actionnav.tsx
- src/pages/detail_post/modify/modifypost.tsx
- src/pages/write_post/index.tsx
thumbnail 수정 안할시 null값으로 들어가는것=> 전에 url가져와서 넣기로 수정
> [feature/actionNav]Refactor: modify page thumbnail 코드 수정

- index.html
- src/components/nav/nav.module.css
- src/components/nav/nav.tsx
- src/components/postcard/postcard.tsx
- src/hooks/use_favoriestatus.tsx
- src/pages/community/postlist/postlist.tsx
- src/pages/detail_post/index.tsx
파비콘 및 메인로고 변경, 400error 오류해결, 콘솔제거
> [feature/category]Fix: 파비콘 및 메인로고 변경, 400error 오류해결, 콘솔제거

- src/pages/chat/get_messages_of_chatroom/get_messages_of_chatroom.tsx
- src/pages/chat/get_my_chat_list/get_chat_list.tsx
- src/pages/chat/index.tsx
- src/pages/detail_post/actionnav.tsx
- src/pages/detail_post/comments/comments.tsx
- src/pages/detail_post/go_to_chat/go_chat.tsx
- src/pages/detail_post/index.tsx
- src/pages/detail_post/modify/modifypost.tsx
- src/pages/login/kakao/kakao.tsx
> [feature/chatting]Chore: axios Headers 제거 ,불필요한 console.log제거

- src/api/axios.ts
- src/pages/chat/index.tsx
- src/pages/main/index.tsx
- src/pages/mypage /likelist/likelist.tsx
- src/pages/mypage /mypost/mypost.tsx
main.mypage 콘솔로그 제거 , axios.ts 오타 수정
> [feature/chatting]Chore: console.log 제거 , axios.ts 오타수정

- src/api/axios.ts
- src/components/nav/logout_handler.tsx
- src/components/nav/nav.tsx
- src/pages/chat/create_chatroom/create_chatroom.tsx
- src/pages/chat/get_messages_of_chatroom/get_messages_of_chatroom.tsx
- src/pages/login/index.tsx
- src/pages/login/kakao/kakao.tsx
> [feature/chatting]Chore: console.log 재확인 및 alert창으로 대체

- src/api/axios.ts
- src/pages/detail_post/index.tsx
> [feature/chatting]Chore: alert 문구 변경

- src/pages/detail_post/modify/modifypost.tsx
respose data가 존재하는지 보고 사진 보내기로 수정
> [feature/actionNav]Refactor: modifyPost type error 수정

- src/pages/detail_post/modify/modifypost.tsx
- src/pages/write_post/index.tsx
undifined로 인한 오류 해결, config 중복으로 인한 오류 해결
> [feature/actionNav]Refactor: modifyPost, writePost type error 해결

- src/components/postcard/favorite/favorite_toggle.tsx
- src/hooks/use_favoriestatus.tsx
> [feature/category]Fix: 찜 버튼 오류 수정

- src/pages/detail_post/modify/modifypost.tsx
- src/pages/mypage /index.module.css
- src/pages/mypage /myprofile/myprofile.tsx
- src/pages/sign_up/index.tsx
프로필 이미지 안보이는 오류 수정, 마이페이지 회원탈퇴css 수정, axios오류로 header추가
> [feature/actioNav]Refactor: myprofile profileImg 오류 및 css 수정, modifyPost axios header 추가

- src/pages/detail_post/favorite_button.tsx
- src/pages/detail_post/index.module.css
- src/pages/detail_post/index.tsx
> [feature/category]Feat: 게시글에서 찜하기 버튼 수정
